# -*- coding: utf-8 -*-
"""Regression Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hYIbZyuuy7Vet5skbF4UpX6C80q02kDg

**Engr. Babu Mal**

# import the libraries
"""

import numpy as py

import matplotlib.pyplot as plt

import pandas as pd

"""# Import the dataset"""

df = pd.read_csv('data.csv')

"""# Exploring Data"""

df

df.shape

df.columns

df.info()

"""# Data Cleaning

Checking Null Values
"""

df.isnull().any()

df.isnull().sum()

df.duplicated().sum()

# Remove irrelevant columns

df = df.drop(columns=['date','country'])

df.columns

"""# Separate dependent and independent feature"""

x = df[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
        'waterfront', 'view', 'condition', 'sqft_above', 'sqft_basement',
        'yr_built', 'yr_renovated', 'street', 'city', 'statezip']]

y = df['price']

x.shape

y.shape

"""# Separating categorical & Numerical columns"""

df_cat=x.select_dtypes("object")
df_num=x.select_dtypes("number")

"""# Encoding of categorical data

Label Encoding
"""

from sklearn.preprocessing import LabelEncoder

#labelencoder = LabelEncoder()

#for col in df_cat.columns:
 #   df_cat[col] = labelencoder.fit_transform(df_cat[col])

#df_cat

"""Dummies Method"""

df_cat_encoded=pd.get_dummies(df_cat,columns=df_cat.columns.to_list(), dtype=int)
df_cat_encoded.head()

# Concatenating encoded categorical data with numerical data
x = pd.concat([df_cat_encoded, df_num], axis=1, join='outer')
x.head()

x.info()

x.shape

"""# Training and Testing Data (divide the data into two part)"""

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2, random_state=0)

x_train.shape

y_train.shape

x_test.shape

y_test.shape

"""# Linear Regression"""

from sklearn.linear_model import LinearRegression

reg = LinearRegression()
#Fit the model
reg.fit(x_train, y_train)

"""## Prediction"""

y_predict1=reg.predict(x_test)

test=pd.DataFrame({
    'Actual':y_test,
    'Y test predicted':y_predict1
})

pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_predict1,'Difference':y_test-y_predict1})
pred_df

"""## Accuracy

"""

print("Accuracy --> ", reg.score(x_test, y_test)*100)

"""## R-Square"""

from sklearn.metrics import mean_squared_error, r2_score
r2_square = r2_score(y_test,y_predict1)
print(f" R-squared: {r2_square}")

"""### Mean Squared Error"""

mse = mean_squared_error(y_test, y_predict1)
print(f'Mean Squared Error: {mse}')

"""# Multiple Regression"""

from sklearn.linear_model import LinearRegression
mreg = LinearRegression()
mreg.fit(x_train,y_train)

"""## Prediction

"""

y_predict2=mreg.predict(x_test)

test=pd.DataFrame({
    'Actual':y_test,
    'Y test predicted':y_predict2
})

pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_predict2,'Difference':y_test-y_predict2})
pred_df

"""## Accuracy"""

print("Accuracy --> ", mreg.score(x_test, y_test)*100)

"""## R-Squared"""

from sklearn.metrics import mean_squared_error, r2_score
r2_square = r2_score(y_test,y_predict2)
print(f" R-squared: {r2_square}")

"""## Mean Squraed Error"""

mse = mean_squared_error(y_test, y_predict2)
print(f'Mean Squared Error: {mse}')

"""# Support Vector Regression"""

from sklearn.svm import SVR
SV_reg = SVR(kernel='rbf')
SV_reg.fit(x, y)

"""## Prediction

"""

y_predict3=mreg.predict(x_test)

test=pd.DataFrame({
    'Actual':y_test,
    'Y test predicted':y_predict3
})

pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_predict3,'Difference':y_test-y_predict3})
pred_df

"""## Accuracy"""

print("Accuracy --> ", mreg.score(x_test, y_test)*100)

"""## R-Squared

"""

from sklearn.metrics import mean_squared_error, r2_score
r2_square = r2_score(y_test,y_predict3)
print(f" R-squared: {r2_square}")

"""## Mean Squared Error"""

mse = mean_squared_error(y_test, y_predict3)
print(f'Mean Squared Error: {mse}')

"""# Random Forest Regression"""

from sklearn.ensemble import RandomForestRegressor
RF_reg = RandomForestRegressor(n_estimators=10,random_state =0)
RF_reg.fit(x, y)

"""## Prediction"""

y_predict4=mreg.predict(x_test)

test=pd.DataFrame({
    'Actual':y_test,
    'Y test predicted':y_predict4
})

pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_predict4,'Difference':y_test-y_predict4})
pred_df

"""## Accuracy"""

print("Accuracy --> ", mreg.score(x_test, y_test)*100)

"""## R-Squared"""

from sklearn.metrics import mean_squared_error, r2_score
r2_square = r2_score(y_test,y_predict4)
print(f" R-squared: {r2_square}")

"""## Mean Squared Error"""

mse = mean_squared_error(y_test, y_predict4)
print(f'Mean Squared Error: {mse}')

"""# Decision Tree Regression"""

from sklearn.tree import DecisionTreeRegressor
DT_reg = DecisionTreeRegressor(random_state =0)
DT_reg.fit(x, y)

"""## Prediction"""

y_predict5=mreg.predict(x_test)

test=pd.DataFrame({
    'Actual':y_test,
    'Y test predicted':y_predict5
})

pred_df=pd.DataFrame({'Actual Value':y_test,'Predicted Value':y_predict5,'Difference':y_test-y_predict5})
pred_df

"""## Accuracy"""

print("Accuracy --> ", mreg.score(x_test, y_test)*100)

"""## R-Squared"""

from sklearn.metrics import mean_squared_error, r2_score
r2_square = r2_score(y_test,y_predict5)
print(f" R-squared: {r2_square}")

"""## Mean Squared Error"""

mse = mean_squared_error(y_test, y_predict5)
print(f'Mean Squared Error: {mse}')